FROM mongo:4.2

#COPY oncodb-20190927.json /oncodb-20190927.json

#CMD mongoimport --host onco-mongo --db ONCDB02D --collection data --drop --file /oncdb02d-20190927.json --jsonArray

ENV TZ Asia/Bangkok
